### ISSUE TITLE
cocoaPods Error

### ISSUE THREAD

**Issue by yuanjilee** [APUtils/ObjectMapperAdditions#1]
with blow error

`
[!] Unable to find a specification for `ObjectMapperAdditions/Core` 
`

**Comment by anton-plebanovich** [comment]
Hey! Try to execute `pod repo update` first.

**Comment by APUtils** [comment]
Did that help @yuanjilee ? If no, you could also try specify git repository in your podfile:
```ruby
pod 'ObjectMapperAdditions/Core', :git => 'https://github.com/APUtils/ObjectMapperAdditions'
```
