### ISSUE TITLE
Realm db fills up with RealmStrings on every network request

### ISSUE THREAD

**Issue by 3ur3ka** [APUtils/ObjectMapperAdditions#2]
Hi,

I'm using code similar to the example for the realm features, and using a map with:
`strings <- (map["strings"], RealmTypeCastTransform<RealmString>())`

However, every time I do (the same) network request to pull down data and insert into realm, I get more and more RealmStrings building up in the db i.e. it doesn't overwrite the existing RealmStrings - is there a way to stop this happening?

Many Thanks

**Comment by anton-plebanovich** [comment]
Hey, thanks for the report, I guess I should deprecate RealmString and other primitives since Realm supports this natively from 3.0 - https://realm.io/blog/realm-cocoa-reaches-3-0/

**Comment by anton-plebanovich** [comment]
For your issue you probably have to delete previous `RealmString`s. Can't be 100% sure though until I have time to investigate.

**Comment by 3ur3ka** [comment]
Thanks Anton,

I tried in the mapping to delete them if the object already exists (and even deleting the object completely):
```  ...
    id <- map["id"]
    if let existingJob = realm.object(ofType: Job.self, forPrimaryKey: id!) {
        existingJob.assignedTo.removeAll()
        existingJob.pointsOfContact.removeAll()
        // realm.delete(existingJob)
    }
    ...
```
but this doesn't seem to delete the RealmStrings, any help would be greatly appreciated :-)

**Comment by anton-plebanovich** [comment]
Hey @3ur3ka, I updated example setter from README. With line `strings.forEach { $0.realm?.delete($0) }` it seems to work correctly.

```
    var _strings: [String] {
        get {
            return strings.map({ $0.value })
        }
        set {
            strings.forEach { $0.realm?.delete($0) }
            strings.removeAll()
            strings.append(objectsIn: newValue.map(RealmString.init(swiftValue:)))
        }
    }
```

Basically you have to delete RealmString objects from real before reassigning them.

**Comment by 3ur3ka** [comment]
All working now, thanks a lot! :-)

**Comment by anton-plebanovich** [comment]
Just pushed latest version `4.0.1`. It can transform `[String]` into `List<String>`. Check README or example project for more details.
