### ISSUE TITLE
Optional Double value transform

### ISSUE THREAD

**Issue by toedwy** [APUtils/ObjectMapperAdditions#3]
Sometimes I do not want to initialize a Double(or Int) value with a specific value, since the '0' maybe has its own meaning(such as 0 degree in temperature description). Therefore, I prefer an optional definition. But now I found that I cannot transform an option value like `@objc dynamic var aValue: Double?` or `@objc dynamic var aValue: RealmOptional<Double>` with `DoubleTransform()`

How can I implement it?

**Comment by anton-plebanovich** [comment]
Hey, I just added `RealmOptionalTransform` and `RealmOptionalTypeCastTransform`. It's available from 4.1 version and you can check README or test project for more details.

**Comment by toedwy** [comment]
@anton-plebanovich 
Thanks for you reply and updates.
I've updated to 4.1 and tried. These new features seem to solve my problem perfectly.
Thanks again！

P.S. There's some format errors appearing at the end of README. Looks like the code block mark ''' tailed at the wrong line.

**Comment by anton-plebanovich** [comment]
Thanks! I didn't notice that one.
