### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by teologov** [APUtils/ObjectMapperAdditions#5]
Hi, I wanted to try using this project but found out it doesn't support macOS. When running pod install there is an error:
```
(macOS 10.14) is not compatible with `ObjectMapperAdditions/Core (6.0.1)`, which does not support `osx`
```

Much appreciated if it's possible to add macOS for this awesome project too. Thanks!

**Comment by anton-plebanovich** [comment]
Thanks for the report, I'm on it

**Comment by teologov** [comment]
Thanks, @anton-plebanovich!

**Comment by anton-plebanovich** [comment]
@teologov `6.0.2` version has support for `macOS`, `tvOS` and `watchOS` for both `Cocoapods` and `Carthage`. Please report back if it won't work for you.

**Comment by teologov** [comment]
@anton-plebanovich wow, such a quick update! Awesome, thank you so much!
