### ISSUE TITLE
Incorrect value of optional Double

### ISSUE THREAD

**Issue by avjiang** [APUtils/ObjectMapperAdditions#7]
Hi, it seems like there is a problem when a property of optional double value has value something like = 0.1

After map it with ObjectMapper then the value becomes 0.100000000001

It won't occur when the value is like 1.01 or other similar number.

**Comment by anton-plebanovich** [comment]
Hi, thanks for the report I'll check this one when I have time available.

**Comment by anton-plebanovich** [comment]
@avjiang I added some test cases to try to reproduce an issue you faced but was unable to catch it for 64-bit nor 32-bit devices. Could you provide a JSON or at least a part of it you were trying to map?

Also, you may checkout the latest commit and perform tests yourself in `TypeCastSpec.swift`. for `Example/ObjectMapperAdditions.xcworkspace`.

**Comment by avjiang** [comment]
First i would like to apologize if this might not be the case from this library. 

I have this model 

    public struct ItemDO {
            public var margin: Double? = 0.00 
    }
   
    // instantiate the object 
    var object = ItemDO()
    object.margin = 0.1

    print("\(object.toJSONString()!)")

I looked at the debugger and it returns me 0.10000000001.  I am not sure why

**Comment by anton-plebanovich** [comment]
I was able to reproduce, thanks! Investigating...

**Comment by anton-plebanovich** [comment]
@avjiang related to this one https://stackoverflow.com/questions/35053577/nsjsonserialization-with-small-decimal-numbers

Sadly, it can be fixed at https://github.com/tristanhimmelman/ObjectMapper only so please report there. Basically, it's more of the Apple issue and happens in `Mapper.swift:389` when using system mapping `JSONData = try JSONSerialization.data(withJSONObject: JSONObject, options: options)` but ye there is a workaround possible.

**Comment by avjiang** [comment]
thanks @anton-plebanovich for the explanation. 

I have raised this issue to the library page. So i guess i have to wait now

Thanks!
