### ISSUE TITLE
not support new version of realm should update library to new realm

### ISSUE THREAD

**Issue by alpesh232** [APUtils/ObjectMapperAdditions#8]

**Comment by anton-plebanovich** [comment]
Thanks for the report, checking

**Comment by anton-plebanovich** [comment]
@alpesh232 I verified `ObjectMapperAdditions` of version `7.0.0` works fine with the latest realm framework `5.2.0`. Could you clarify the problem you faced?

**Comment by Drusy** [comment]
Hi @anton-plebanovich.since Realm v10, we get the following warning:

> 'RealmOptional' is deprecated: RealmOptional<T> has been deprecated, use RealmProperty<T?> instead.

It would be nice to switch to RealmProperty. Tried myself without any big success ...

**Comment by Drusy** [comment]
I think it would be something like

```swift
/// Transforms Swift numeric Optional to Realm numberic Optional. E.g. Int? to RealmOptional<Int>.
/// Additionally, it will type cast value if type mismatches. E.g. "123" String to 123 Int.
public class RealmOptionalTypeCastTransform<T: _RealmSchemaDiscoverable & RealmOptionalType>: TransformType {
    public typealias Object = RealmProperty<T?>
    public typealias JSON = Any
    
    public init() {}
    
    public func transformFromJSON(_ value: Any?) -> Object? {
        let typeCastTransform = TypeCastTransform<T>()
        let castedValue = typeCastTransform.transformFromJSON(value)
        let realmOptional = RealmProperty<T?>()
        
        realmOptional.value = castedValue
        
        return realmOptional
    }
    
    public func transformToJSON(_ value: Object?) -> Any? {
        return value?.value
    }
}
```

**Comment by anton-plebanovich** [comment]
Hi @Drusy , thanks for the report, I'll check that tomorrow

**Comment by anton-plebanovich** [comment]
Hi @Drusy the new `8.1.0` version is released with `RealmPropertyTransform` and `RealmPropertyTypeCastTransform` added. Please check and reopen if it still doesn't work for you.
